[tool.poetry]
name = "segmentace-bunek"
version = "0.1.0"
description = ""
authors = ["yoptohlejepeta <peta.kotlan@seznam.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mahotas = "^1.4.18"
matplotlib = "^3.9.2"
numpy = "^2.1.2"
pandas = "^2.2.3"
pillow = "^10.4.0"
scikit-image = "^0.24.0"
opencv-python = "^4.10.0.84"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
